language: python
python:
- '3.6.5'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database andela;' -U postgres
script:
- pytest --cov=food_api
- coveralls
after_success:
- coveralls
