
language: python
python:
  - "3.6.5"

install:

 - pip install -r requirements.txt

 services:

  - postgresql

before_script:

- psql - c 'create database andela;' -U postgres

addons:
  postgresql: "9.4"

scripts:
- pytest --cov=.
- coveralls

after_success:
- coveralls