language: python
python:
- '3.6.5'
sudo: false
cache: pip3
install:
- pip install -r requirements.txt

services:

  - postgresql

before_script:

- psql -c 'create database andela;' -U postgres

addons:
  postgresql: "9.4"



script:
- pytest --cov=.
- coverage
- coveralls
- coverage report
after_success:
- coveralls

